version: '3'

volumes:
  pgdata:
  redisdata:
  auto-mapper-pgdata:

services:
  postgres:
    image: postgres
    # restart: always
    container_name: 'RTM_POSTGRES'
    environment:
      POSTGRES_PASSWORD: sails
      POSTGRES_USER: sails
      POSTGRES_DB: report-type-mapper
    ports:
      - "5432:5432"
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

  api:
    build: ./api
    container_name: RTM_Backend
    volumes:
      - ./api:/app
      - /app/node_modules/ #empties container node_modules, forces bcrypt to be built on container
    ports:
      - "1337:1337"
    depends_on:
      - postgres
      - redis
    # env_file: .env
    environment:
      - NODE_ENV=development
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   container_name: RTM_Frontend
  #   volumes:
  #     - ./client:/app
  #   ports:
  #     - "8000:8000"
  auto-mapper-api:
    container_name: AUTO_MAPPER_API
    build:
      context: ./auto-mapper
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - auto-mapper-pg
    volumes:
      - ./auto-mapper:/api
  auto-mapper-pg:
    image: postgres
    container_name: 'AUTO_MAPPER_PG'
    environment:
      POSTGRES_PASSWORD: pg
      POSTGRES_USER: pg
      POSTGRES_DB: postgres
    ports:
      - "5433:5433"
    volumes:
      - 'auto-mapper-pgdata:/var/lib/postgresql/data/'
  redis:
    image: redis:3.2.0
    container_name: RTM_Redis
    ports:
      - "6379:6379"
    volumes:
    - 'redisdata:/data'
  swagger:
    image: swaggerapi/swagger-ui
    container_name: RTM_Swagger_Docs
    environment:
    - "API_URL=http://localhost:1337/v1/swagger.json"
    ports:
      - "3000:8080"
