version: '3'

volumes:
  pgdata:
  redisdata:

services:
  postgres:
    image: postgres
    #restart: always
    container_name: 'RTM_POSTGRES'
    environment:
      POSTGRES_PASSWORD: sails
      POSTGRES_USER: sails
      POSTGRES_DB: report-type-mapper
    ports:
      - "5432:5432"
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
  api:
    # image: ${PRIVATE_REGISTRY}/rtm-api:rtm-api
    build: ./api
    container_name: RTM_Backend
    ports:
      - "1337:1337"
    depends_on:
      - postgres
      - redis
    # env_file: .env
    environment:
      - NODE_ENV=development
    command: "pm2-runtime app.js"
  client:
    # image: ${PRIVATE_REGISTRY}/rtm-client:rtm-api
    build: ./client
    container_name: RTM_Frontend
    command: "npm start"
    ports:
      - "80:8000"
  redis:
    image: redis:3.2.0
    container_name: RTM_Redis
    ports:
      - "6379:6379"
  swagger:
    image: swaggerapi/swagger-ui
    container_name: RTM_Swagger_Docs
    environment:
    - "API_URL=http://104.131.34.144:1337/v1/swagger.json"
    ports:
      - "3000:8080"
